spring:
  application:
    name: cursos

  # Configuración de MongoDB Atlas para WebFlux
  data:
    mongodb:
      uri: mongodb+srv://fockio94:PgjFLYVB0lya5uD7@cluster0.zjkoq.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: colegio

  # Puerto en el que se ejecuta el microservicio
server:
  port: 8082

# Configuración de Eureka para el registro del servicio
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
