spring:
  application:
    name: kafka 

  # Puerto en el que se ejecuta el microservicio
server:
  port: 8083

# Configuración de Eureka para el registro del servicio
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
